name: Backend CI/CD

on:
  push:
    branches:
      - main 
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore ./backend

      - name: Run Unit Tests
        run: dotnet test ./backend --verbosity normal

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/gestao-livros:latest ./backend

      - name: Login to GHCR
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/gestao-livros:latest
